import { RssNewsProvider } from '../providers/RssNewsProvider';
import { INewsProvider } from '../interfaces/INewsProvider';

export const rssProviders: INewsProvider[] = [
	new RssNewsProvider('Clarín', [
		'https://www.clarin.com/rss/lo-ultimo/',
		'https://www.clarin.com/rss/politica/',
		'https://www.clarin.com/rss/mundo/',
		'https://www.clarin.com/rss/sociedad/',
		'https://www.clarin.com/rss/policiales/',
		'https://www.clarin.com/rss/opinion/',
		'https://www.clarin.com/rss/cartas_al_pais/',
		'https://www.clarin.com/rss/cultura/',
		'https://www.clarin.com/rss/rural/',
		'https://www.clarin.com/rss/economia/',
		'https://www.clarin.com/rss/tecnologia/',
	]),
	new RssNewsProvider('Página/12', [
		'https://www.pagina12.com.ar/rss/portada',
		'https://www.pagina12.com.ar/rss/secciones/el-pais/notas',
		'https://www.pagina12.com.ar/rss/secciones/economia/notas',
		'https://www.pagina12.com.ar/rss/secciones/sociedad/notas',
		'https://www.pagina12.com.ar/rss/secciones/el-mundo/notas',
		'https://www.pagina12.com.ar/rss/secciones/cultura/notas',
		'https://www.pagina12.com.ar/rss/secciones/universidad/notas',
		'https://www.pagina12.com.ar/rss/secciones/ciencia/notas',
		'https://www.pagina12.com.ar/rss/secciones/psicologia/notas',
		'https://www.pagina12.com.ar/rss/secciones/dialogos/notas',
		'https://www.pagina12.com.ar/rss/secciones/hoy/notas',
		'https://www.pagina12.com.ar/rss/suplementos/cash/notas',
		'https://www.pagina12.com.ar/rss/suplementos/las12/notas',
	]),
	new RssNewsProvider('Infobae', ['https://www.infobae.com/arc/outboundfeeds/rss/']),
	new RssNewsProvider('TN', ['https://www.tn.com.ar/rss.xml']),
	// new RssNewsProvider('La Nación', ['https://www.lanacion.com.ar/rss/']),
	new RssNewsProvider('La Voz', [
		'http://archivo.lavoz.com.ar/Rss/Rss.asp?origen=1',
		'http://archivo.lavoz.com.ar/Rss/Rss.asp?categoria=47',
		'http://archivo.lavoz.com.ar/Rss/Rss.asp?categoria=213',
		'http://archivo.lavoz.com.ar/Rss/Rss.asp?categoria=214',
		'http://archivo.lavoz.com.ar/Rss/Rss.asp?categoria=48',
		'http://archivo.lavoz.com.ar/Rss/Rss.asp?categoria=17',
		'http://archivo.lavoz.com.ar/Rss/Rss.asp?categoria=16',
		'http://archivo.lavoz.com.ar/Rss/Rss.asp?categoria=34',
	]),
	new RssNewsProvider('El Cronista', ['https://www.cronista.com/files/rss/news.xml']),
	new RssNewsProvider('Ámbito', [
		'https://www.ambito.com/rss/pages/ultimas-noticias.xml',
		'https://www.ambito.com/rss/pages/home.xml',
		'https://www.ambito.com/rss/pages/economia.xml',
		'https://www.ambito.com/rss/pages/negocios.xml',
		'https://www.ambito.com/rss/pages/nacional.xml',
		'https://www.ambito.com/rss/pages/municipios.xml',
		'https://www.ambito.com/rss/pages/finanzas.xml',
		'https://www.ambito.com/rss/pages/politica.xml',
		'https://www.ambito.com/rss/pages/mundo.xml',
		'https://www.ambito.com/rss/pages/tecnologia.xml',
		'https://www.ambito.com/rss/pages/novedades-fiscales.xml    ',
	]),
	new RssNewsProvider('Perfil', [
		'https://www.perfil.com/feed',
		'https://www.perfil.com/feed/politica',
		'https://www.perfil.com/feed/policia',
		'https://www.perfil.com/feed/economia',
		'https://www.perfil.com/feed/deportes',
		'https://www.perfil.com/feed/tecnologia',
		'https://www.perfil.com/feed/cultura',
		'https://www.perfil.com/feed/opinion',
		'https://www.perfil.com/feed/sociedad',
		'https://www.perfil.com/feed/espectaculos',
		'https://www.perfil.com/feed/ciencia',
		'https://www.perfil.com/feed/salud',
	]),
	new RssNewsProvider('El País', [
		'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/ultimas-noticias/portada',
		'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/lo-mas-visto/portada',
		'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/sociedad/portada',
		'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/internacional/portada',
		'https://feeds.elpais.com/mrss-s/list/ep/site/elpais.com/section/opinion',
		'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/economia/portada',
		'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/ciencia/portada',
		'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/tecnologia/portada',
		'https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/section/cultura/portada',
		'https://feeds.elpais.com/mrss-s/list/ep/site/elpais.com/section/educacion',
	]),
	new RssNewsProvider('La Vanguardia', [
		'https://www.lavanguardia.com/rss/home.xml',
		'https://www.lavanguardia.com/rss/internacional.xml',
		'https://www.lavanguardia.com/rss/politica.xml',
		'https://www.lavanguardia.com/rss/vida.xml',
		'https://www.lavanguardia.com/rss/economia.xml',
		'https://www.lavanguardia.com/rss/opinion.xml',
		'https://www.lavanguardia.com/rss/cultura.xml',
		'https://www.lavanguardia.com/rss/gente.xml',
		'https://www.lavanguardia.com/rss/sucesos.xml',
		'https://www.lavanguardia.com/rss/participacion.xml',
	]),
	// periodicos de argentina
	new RssNewsProvider('El Tribuno', [
		'https://www.eltribuno.com/rss-new/portada.rss',
		'https://www.eltribuno.com/rss-new/sociedad.rss',
		'https://www.eltribuno.com/rss-new/politica.rss',
		'https://www.eltribuno.com/rss-new/policiales.rss',
		'https://www.eltribuno.com/rss-new/internacionales.rss',
		'https://www.eltribuno.com/rss-new/salta.rss',
		'https://www.eltribuno.com/rss-new/nacionales.rss',
		'https://www.eltribuno.com/rss-new/vida-y-tendencia.rss',
		'https://www.eltribuno.com/rss-new/municipios.rss',
	]),
];
